#include "LudoFilterSystem.h"

#include <QtGlobal>
#include <cmath>
#include <cstring>

namespace game {
namespace {
double smooth01(double t){t=qBound(0.0,t,1.0);return t*t*(3.0-2.0*t);} 
double smoothRange(double a,double b,double x){return b<=a?(x>=b?1.0:0.0):smooth01((x-a)/(b-a));}
int mix8(int a,int b,double t){return qBound(0,int(std::lround(a+(b-a)*t)),255);} 
quint32 hash32(quint32 x){x^=x>>16;x*=0x7feb352du;x^=x>>15;x*=0x846ca68bu;x^=x>>16;return x;}
double hashNoiseSeeded(int x,int y,int seed){const quint32 h=hash32(quint32(x)*0x9e3779b1u^quint32(y)*0x85ebca6bu^quint32(seed)*0xc2b2ae35u);return (double(h&0xffffu)/65535.0)*2.0-1.0;}
double valueNoise(double x,double y,int seed){const int x0=int(std::floor(x)),y0=int(std::floor(y));const double fx=smooth01(x-x0),fy=smooth01(y-y0);const double a=hashNoiseSeeded(x0,y0,seed),b=hashNoiseSeeded(x0+1,y0,seed),c=hashNoiseSeeded(x0,y0+1,seed),d=hashNoiseSeeded(x0+1,y0+1,seed);const double ab=a+(b-a)*fx,cd=c+(d-c)*fx;return ab+(cd-ab)*fy;}
double filmNoise(double x,double y,int seed){const double a=valueNoise(x,y,seed),b=valueNoise(x*2.31+17.0,y*2.31-9.0,seed+101);return qBound(-1.0,(a+b*.35)/1.35,1.0);}
double shapedNoise(double n,double contrast){return qBound(-1.0,n*qBound(.25,contrast,4.0),1.0);}
double temporalFilmNoise(double px,double py,const core::NoiseFilterConfig&n,double time,int seedOffset){const int seed=n.seed+seedOffset;switch(n.temporalMode){case core::NoiseTemporalMode::Static:return filmNoise(px,py,seed);case core::NoiseTemporalMode::Drift:{const double t=time*n.speed;return filmNoise(px+t*1.7,py+t*.93,seed);}case core::NoiseTemporalMode::Smooth:{const double p=time*n.speed*12.0;const int a=int(std::floor(p));const double f=smooth01(p-a);const double n0=filmNoise(px,py,seed+a*37),n1=filmNoise(px,py,seed+(a+1)*37);return n0+(n1-n0)*f;}default:{const int phase=int(std::floor(time*n.speed*24.0));return filmNoise(px,py,seed+phase*37);}}}
double temporalLegacyNoise(int gx,int gy,const core::NoiseFilterConfig&n,double time,int seedOffset){int phase=0;if(n.temporalMode!=core::NoiseTemporalMode::Static)phase=int(std::floor(time*n.speed*24.0));const quint32 h=hash32(quint32(gx)*0x9e3779b1u^quint32(gy)*0x85ebca6bu^quint32(phase+n.seed+seedOffset));return (double(h&0xffffu)/65535.0)*2.0-1.0;}
int slotClamp(int slot){return qBound(core::LudoFilterMinSlot,slot,core::LudoFilterMaxSlot);}

template<class C> void beginTransition(FilterTransitionChannel<C>& ch,C target,double duration){ch.from=ch.current;ch.target=target;ch.from.scope=target.scope;ch.current.scope=target.scope;ch.elapsed=0;ch.duration=qMax(0.0,duration);ch.transitioning=ch.duration>0;if(!ch.transitioning)ch.current=ch.target;}

core::ChromaticAberrationConfig lerpConfig(const core::ChromaticAberrationConfig&a,const core::ChromaticAberrationConfig&b,double t){auto o=b;o.intensityPixels=a.intensityPixels+(b.intensityPixels-a.intensityPixels)*t;o.edgeStart=a.edgeStart+(b.edgeStart-a.edgeStart)*t;o.falloff=a.falloff+(b.falloff-a.falloff)*t;o.mix=a.mix+(b.mix-a.mix)*t;o.normalize();return o;}
core::NoiseFilterConfig lerpConfig(const core::NoiseFilterConfig&a,const core::NoiseFilterConfig&b,double t){auto o=b;o.intensity=a.intensity+(b.intensity-a.intensity)*t;o.grainSizePixels=a.grainSizePixels+(b.grainSizePixels-a.grainSizePixels)*t;o.speed=a.speed+(b.speed-a.speed)*t;o.contrast=a.contrast+(b.contrast-a.contrast)*t;o.colorAmount=a.colorAmount+(b.colorAmount-a.colorAmount)*t;o.normalize();return o;}
core::ScanlineFilterConfig lerpConfig(const core::ScanlineFilterConfig&a,const core::ScanlineFilterConfig&b,double t){auto o=b;o.intensity=a.intensity+(b.intensity-a.intensity)*t;o.spacingPixels=a.spacingPixels+(b.spacingPixels-a.spacingPixels)*t;o.thickness=a.thickness+(b.thickness-a.thickness)*t;o.softness=a.softness+(b.softness-a.softness)*t;o.phasePixels=a.phasePixels+(b.phasePixels-a.phasePixels)*t;o.scrollSpeed=a.scrollSpeed+(b.scrollSpeed-a.scrollSpeed)*t;o.interlaceAmount=a.interlaceAmount+(b.interlaceAmount-a.interlaceAmount)*t;o.interlaceSpeed=a.interlaceSpeed+(b.interlaceSpeed-a.interlaceSpeed)*t;o.sweepSpeed=a.sweepSpeed+(b.sweepSpeed-a.sweepSpeed)*t;o.sweepWidth=a.sweepWidth+(b.sweepWidth-a.sweepWidth)*t;o.sweepSoftness=a.sweepSoftness+(b.sweepSoftness-a.sweepSoftness)*t;o.sweepIntensity=a.sweepIntensity+(b.sweepIntensity-a.sweepIntensity)*t;o.sweepRed=int(std::lround(a.sweepRed+(b.sweepRed-a.sweepRed)*t));o.sweepGreen=int(std::lround(a.sweepGreen+(b.sweepGreen-a.sweepGreen)*t));o.sweepBlue=int(std::lround(a.sweepBlue+(b.sweepBlue-a.sweepBlue)*t));o.sweepDelaySeconds=a.sweepDelaySeconds+(b.sweepDelaySeconds-a.sweepDelaySeconds)*t;o.normalize();return o;}
core::VignetteFilterConfig lerpConfig(const core::VignetteFilterConfig&a,const core::VignetteFilterConfig&b,double t){auto o=b;o.intensity=a.intensity+(b.intensity-a.intensity)*t;o.radius=a.radius+(b.radius-a.radius)*t;o.softness=a.softness+(b.softness-a.softness)*t;o.normalize();return o;}
core::BlurFilterConfig lerpConfig(const core::BlurFilterConfig&a,const core::BlurFilterConfig&b,double t){auto o=b;o.radiusPixels=a.radiusPixels+(b.radiusPixels-a.radiusPixels)*t;o.strength=a.strength+(b.strength-a.strength)*t;o.edgePreservation=a.edgePreservation+(b.edgePreservation-a.edgePreservation)*t;o.angleDegrees=a.angleDegrees+(b.angleDegrees-a.angleDegrees)*t;o.normalize();return o;}
core::TiltShiftFilterConfig lerpConfig(const core::TiltShiftFilterConfig&a,const core::TiltShiftFilterConfig&b,double t){auto o=b;o.blurPixels=a.blurPixels+(b.blurPixels-a.blurPixels)*t;o.centerY=a.centerY+(b.centerY-a.centerY)*t;o.focusWidth=a.focusWidth+(b.focusWidth-a.focusWidth)*t;o.falloff=a.falloff+(b.falloff-a.falloff)*t;o.strength=a.strength+(b.strength-a.strength)*t;o.edgePreservation=a.edgePreservation+(b.edgePreservation-a.edgePreservation)*t;o.angleDegrees=a.angleDegrees+(b.angleDegrees-a.angleDegrees)*t;o.upperBlurAmount=a.upperBlurAmount+(b.upperBlurAmount-a.upperBlurAmount)*t;o.lowerBlurAmount=a.lowerBlurAmount+(b.lowerBlurAmount-a.lowerBlurAmount)*t;o.normalize();return o;}

template<class C> bool updateChannel(FilterTransitionChannel<C>&ch,double dt){if(!ch.transitioning)return false;ch.elapsed+=qMax(0.0,dt);const double t=smooth01(ch.duration<=0?1:ch.elapsed/ch.duration);ch.current=lerpConfig(ch.from,ch.target,t);if(ch.elapsed>=ch.duration){ch.current=ch.target;ch.transitioning=false;}return true;}
template<class C> bool updateMap(QMap<int,FilterTransitionChannel<C>>&m,double dt){bool changed=false;for(auto it=m.begin();it!=m.end();++it)changed=updateChannel(it.value(),dt)||changed;for(auto it=m.begin();it!=m.end();){if(!it.value().transitioning&&!it.value().current.active()&&!it.value().target.active())it=m.erase(it);else ++it;}return changed;}
template<class C> C effective(const QMap<int,FilterTransitionChannel<C>>&m){auto it=m.constEnd();while(it!=m.constBegin()){--it;if(it.value().current.active())return it.value().current;}return C{};}
template<class C> int effectiveSlot(const QMap<int,FilterTransitionChannel<C>>&m){auto it=m.constEnd();while(it!=m.constBegin()){--it;if(it.value().current.active())return it.key();}return 0;}
template<class C> int activeCount(const QMap<int,FilterTransitionChannel<C>>&m){int n=0;for(auto it=m.cbegin();it!=m.cend();++it)if(it.value().current.active())++n;return n;}
template<class C> bool transitioning(const QMap<int,FilterTransitionChannel<C>>&m){for(auto it=m.cbegin();it!=m.cend();++it)if(it.value().transitioning)return true;return false;}
template<class C> bool mapAffects(const QMap<int,FilterTransitionChannel<C>>&m,core::FilterRenderDomain d){const C c=effective(m);return c.active()&&c.scope.includes(d);}
template<class C> bool mapFull(const QMap<int,FilterTransitionChannel<C>>&m){constexpr int all=7;const C c=effective(m);return !c.active()||c.scope.mask()==all;}

template<class C> QJsonObject channelJson(const FilterTransitionChannel<C>&c){return {{QStringLiteral("current"),QJsonObject::fromVariantMap(c.current.toVariantMap())},{QStringLiteral("from"),QJsonObject::fromVariantMap(c.from.toVariantMap())},{QStringLiteral("target"),QJsonObject::fromVariantMap(c.target.toVariantMap())},{QStringLiteral("elapsed"),c.elapsed},{QStringLiteral("duration"),c.duration},{QStringLiteral("transitioning"),c.transitioning}};}
template<class C> QJsonObject mapJson(const QMap<int,FilterTransitionChannel<C>>&m){QJsonObject o;for(auto it=m.cbegin();it!=m.cend();++it)o.insert(QString::number(it.key()),channelJson(it.value()));return o;}
template<class C,class F> void channelRead(FilterTransitionChannel<C>&c,const QJsonObject&o,F f){c={};if(o.isEmpty())return;c.current=f(o.value(QStringLiteral("current")).toObject().toVariantMap());c.from=f(o.value(QStringLiteral("from")).toObject().toVariantMap());c.target=f(o.value(QStringLiteral("target")).toObject().toVariantMap());c.elapsed=qMax(0.0,o.value(QStringLiteral("elapsed")).toDouble());c.duration=qMax(0.0,o.value(QStringLiteral("duration")).toDouble());c.elapsed=qMin(c.elapsed,c.duration);c.transitioning=o.value(QStringLiteral("transitioning")).toBool(false)&&c.duration>0&&c.elapsed<c.duration;if(!c.transitioning&&o.value(QStringLiteral("transitioning")).toBool(false))c.current=c.target;}
template<class C,class F> void mapRead(QMap<int,FilterTransitionChannel<C>>&m,const QJsonObject&o,F f){for(auto it=o.begin();it!=o.end();++it){bool ok=false;const int slot=it.key().toInt(&ok);if(!ok||slot<1||slot>99)continue;FilterTransitionChannel<C> c;channelRead(c,it.value().toObject(),f);if(c.current.active()||c.target.active()||c.transitioning)m.insert(slot,c);}}

template<class C,class Zero> void clearOne(QMap<int,FilterTransitionChannel<C>>&m,int slot,double duration,Zero zero){auto doIt=[&](FilterTransitionChannel<C>&ch){C target=ch.current;zero(target);beginTransition(ch,target,duration);};if(slot>0){auto it=m.find(slotClamp(slot));if(it!=m.end())doIt(it.value());return;}for(auto it=m.begin();it!=m.end();++it)doIt(it.value());}

double scanSweepPosition(double elapsed,const core::ScanlineFilterConfig&c,bool*visible=nullptr){
    if(c.sweepSpeed<=0){if(visible)*visible=false;return 0;}
    const double halfBand=qMax(.005,c.sweepWidth);
    const double path=1.0+halfBand*2.0;
    const double travel=path/c.sweepSpeed;
    const double cycle=travel+c.sweepDelaySeconds;
    const double phase=cycle>0?std::fmod(qMax(0.0,elapsed),cycle):0;
    const bool on=phase<travel;
    if(visible)*visible=on;
    return on?(-halfBand+phase*c.sweepSpeed):0;
}
void ensureScratch(QImage&scratch,const QImage&frame){if(scratch.size()!=frame.size()||scratch.format()!=frame.format())scratch=QImage(frame.size(),frame.format());for(int y=0;y<frame.height();++y)memcpy(scratch.scanLine(y),frame.constScanLine(y),size_t(frame.bytesPerLine()));}
QRgb gaussian5Sample(const QImage&src,int x,int y,double radius,bool horizontal){
    static constexpr double weights[3]={.375,.25,.0625};
    const double step=qMax(.5,radius*.25);
    double rr=0,gg=0,bb=0,aa=0;
    for(int i=-2;i<=2;++i){
        const int sx=qBound(0,x+(horizontal?int(std::lround(i*step)):0),src.width()-1);
        const int sy=qBound(0,y+(horizontal?0:int(std::lround(i*step))),src.height()-1);
        const QRgb q=reinterpret_cast<const QRgb*>(src.constScanLine(sy))[sx];
        const double w=weights[std::abs(i)];rr+=qRed(q)*w;gg+=qGreen(q)*w;bb+=qBlue(q)*w;aa+=qAlpha(q)*w;
    }
    return qRgba(qBound(0,int(std::lround(rr)),255),qBound(0,int(std::lround(gg)),255),qBound(0,int(std::lround(bb)),255),qBound(0,int(std::lround(aa)),255));
}
void gaussian5Pass(const QImage&src,QImage&dst,bool horizontal,double radius,const core::TiltShiftFilterConfig*tilt=nullptr){
    const int w=src.width(),h=src.height();
    for(int y=0;y<h;++y){
        double rowRadius=radius;
        if(tilt){
            const double yn=(y+.5)/qMax(1.0,double(h));
            const double d=qMax(0.0,std::abs(yn-tilt->centerY)-tilt->focusWidth*.5);
            const double amount=smoothRange(0.0,tilt->falloff,d);
            rowRadius=tilt->blurPixels*amount;
        }
        QRgb* out=reinterpret_cast<QRgb*>(dst.scanLine(y));
        if(rowRadius<=.0001){memcpy(out,src.constScanLine(y),size_t(src.bytesPerLine()));continue;}
        for(int x=0;x<w;++x)out[x]=gaussian5Sample(src,x,y,rowRadius,horizontal);
    }
}
int blurHalfWidth(core::BlurQuality q){switch(q){case core::BlurQuality::Low:return 1;case core::BlurQuality::High:return 3;case core::BlurQuality::Ultra:return 4;default:return 2;}}
double luma8(QRgb q){return (qRed(q)*.2126+qGreen(q)*.7152+qBlue(q)*.0722)/255.0;}
double modernBlurWeight(int i,int half,core::BlurStyle style){if(style==core::BlurStyle::Box)return 1.0;const double sigma=style==core::BlurStyle::GaussianSharp?qMax(.65,half*.55):qMax(1.0,half*.9);return std::exp(-(double(i*i))/(2.0*sigma*sigma));}
QRgb modernBlurSample1D(const QImage&src,int x,int y,double dx,double dy,const core::BlurFilterConfig&c){const int half=blurHalfWidth(c.quality);const double step=c.radiusPixels/qMax(1,half);const QRgb center=reinterpret_cast<const QRgb*>(src.constScanLine(y))[x];const double centerL=luma8(center);double rr=0,gg=0,bb=0,aa=0,total=0;for(int i=-4;i<=4;++i){if(std::abs(i)>half)continue;const int sx=qBound(0,int(std::lround(x+dx*i*step)),src.width()-1),sy=qBound(0,int(std::lround(y+dy*i*step)),src.height()-1);const QRgb q=reinterpret_cast<const QRgb*>(src.constScanLine(sy))[sx];double w=modernBlurWeight(i,half,c.style);if(c.edgePreservation>0)w*=std::exp(-std::abs(luma8(q)-centerL)*c.edgePreservation*12.0);rr+=qRed(q)*w;gg+=qGreen(q)*w;bb+=qBlue(q)*w;aa+=qAlpha(q)*w;total+=w;}if(total<=0)return center;return qRgba(qBound(0,int(std::lround(rr/total)),255),qBound(0,int(std::lround(gg/total)),255),qBound(0,int(std::lround(bb/total)),255),qBound(0,int(std::lround(aa/total)),255));}
QRgb modernBlurSample2D(const QImage&src,int x,int y,const core::BlurFilterConfig&c){const int half=blurHalfWidth(c.quality);const double step=c.radiusPixels/qMax(1,half);const QRgb center=reinterpret_cast<const QRgb*>(src.constScanLine(y))[x];const double centerL=luma8(center);double rr=0,gg=0,bb=0,aa=0,total=0;for(int yy=-4;yy<=4;++yy){if(std::abs(yy)>half)continue;for(int xx=-4;xx<=4;++xx){if(std::abs(xx)>half)continue;const int sx=qBound(0,int(std::lround(x+xx*step)),src.width()-1),sy=qBound(0,int(std::lround(y+yy*step)),src.height()-1);const QRgb q=reinterpret_cast<const QRgb*>(src.constScanLine(sy))[sx];double w=modernBlurWeight(xx,half,c.style)*modernBlurWeight(yy,half,c.style);if(c.edgePreservation>0)w*=std::exp(-std::abs(luma8(q)-centerL)*c.edgePreservation*12.0);rr+=qRed(q)*w;gg+=qGreen(q)*w;bb+=qBlue(q)*w;aa+=qAlpha(q)*w;total+=w;}}if(total<=0)return center;return qRgba(qBound(0,int(std::lround(rr/total)),255),qBound(0,int(std::lround(gg/total)),255),qBound(0,int(std::lround(bb/total)),255),qBound(0,int(std::lround(aa/total)),255));}
void modernBlurPass(const QImage&src,QImage&dst,const core::BlurFilterConfig&c){const int w=src.width(),h=src.height();const double rad=c.angleDegrees*3.14159265358979323846/180.0;const double dx=std::cos(rad),dy=std::sin(rad);for(int y=0;y<h;++y){QRgb*out=reinterpret_cast<QRgb*>(dst.scanLine(y));for(int x=0;x<w;++x){const QRgb original=reinterpret_cast<const QRgb*>(src.constScanLine(y))[x];QRgb blurred=original;if(c.style==core::BlurStyle::Pixel){const int block=qMax(1,int(std::lround(c.radiusPixels)));const int sx=qBound(0,(x/block)*block+block/2,w-1),sy=qBound(0,(y/block)*block+block/2,h-1);blurred=reinterpret_cast<const QRgb*>(src.constScanLine(sy))[sx];}else if(c.style==core::BlurStyle::Directional)blurred=modernBlurSample1D(src,x,y,dx,dy,c);else if(c.direction==core::BlurDirection::Horizontal)blurred=modernBlurSample1D(src,x,y,1,0,c);else if(c.direction==core::BlurDirection::Vertical)blurred=modernBlurSample1D(src,x,y,0,1,c);else blurred=modernBlurSample2D(src,x,y,c);out[x]=qRgba(mix8(qRed(original),qRed(blurred),c.strength),mix8(qGreen(original),qGreen(blurred),c.strength),mix8(qBlue(original),qBlue(blurred),c.strength),mix8(qAlpha(original),qAlpha(blurred),c.strength));}}}
double tiltSignedDistance(int x,int y,int w,int h,const core::TiltShiftFilterConfig&c){const double ux=(x+.5)/qMax(1.0,double(w)),uy=(y+.5)/qMax(1.0,double(h));const double rad=c.angleDegrees*3.14159265358979323846/180.0;const double nx=-std::sin(rad),ny=std::cos(rad);return (ux-.5)*nx+(uy-c.centerY)*ny;}
double tiltBlurAmount(int x,int y,int w,int h,const core::TiltShiftFilterConfig&c,double*sideScale=nullptr){const double sd=tiltSignedDistance(x,y,w,h,c);if(sideScale)*sideScale=sd<0?c.upperBlurAmount:c.lowerBlurAmount;const double d=qMax(0.0,std::abs(sd)-c.focusWidth*.5);return smoothRange(0.0,c.falloff,d);}
void modernTiltPass(const QImage&src,QImage&dst,const core::TiltShiftFilterConfig&c){const int w=src.width(),h=src.height();core::BlurFilterConfig bc;bc.direction=core::BlurDirection::Full;bc.quality=c.quality;bc.strength=1.0;bc.edgePreservation=c.edgePreservation;bc.style=c.style==core::TiltShiftStyle::GaussianSharp?core::BlurStyle::GaussianSharp:(c.style==core::TiltShiftStyle::Box?core::BlurStyle::Box:core::BlurStyle::GaussianSoft);for(int y=0;y<h;++y){QRgb*out=reinterpret_cast<QRgb*>(dst.scanLine(y));for(int x=0;x<w;++x){double side=1.0;const double amount=tiltBlurAmount(x,y,w,h,c,&side);const QRgb original=reinterpret_cast<const QRgb*>(src.constScanLine(y))[x];bc.radiusPixels=c.blurPixels*amount*side;if(bc.radiusPixels<=.0001){out[x]=original;continue;}const QRgb blurred=modernBlurSample2D(src,x,y,bc);const double mix=c.strength*amount;out[x]=qRgba(mix8(qRed(original),qRed(blurred),mix),mix8(qGreen(original),qGreen(blurred),mix),mix8(qBlue(original),qBlue(blurred),mix),mix8(qAlpha(original),qAlpha(blurred),mix));}}}

}

void LudoFilterSystem::reset(){m_chromatic.clear();m_noise.clear();m_scanlines.clear();m_scanlineSweepAge.clear();m_vignette.clear();m_blur.clear();m_tiltShift.clear();m_timeSeconds=0;}
void LudoFilterSystem::setChromaticAberration(core::ChromaticAberrationConfig c,double d,int s){c.normalize();beginTransition(m_chromatic[slotClamp(s)],c,d);}
void LudoFilterSystem::setNoise(core::NoiseFilterConfig c,double d,int s){c.normalize();beginTransition(m_noise[slotClamp(s)],c,d);}
void LudoFilterSystem::setScanlines(core::ScanlineFilterConfig c,double d,int s){c.normalize();const int slot=slotClamp(s);beginTransition(m_scanlines[slot],c,d);if(c.whiteSweep&&c.sweepIntensity>.0001&&c.sweepSpeed>.0001)m_scanlineSweepAge[slot]=0.0;else m_scanlineSweepAge.remove(slot);}
void LudoFilterSystem::setVignette(core::VignetteFilterConfig c,double d,int s){c.normalize();beginTransition(m_vignette[slotClamp(s)],c,d);}
void LudoFilterSystem::setBlur(core::BlurFilterConfig c,double d,int s){c.normalize();beginTransition(m_blur[slotClamp(s)],c,d);}
void LudoFilterSystem::setTiltShift(core::TiltShiftFilterConfig c,double d,int s){c.normalize();beginTransition(m_tiltShift[slotClamp(s)],c,d);}
void LudoFilterSystem::clearChromaticAberration(double d,int s){clearOne(m_chromatic,s,d,[](auto&c){c.intensityPixels=0;c.mix=0;});}void LudoFilterSystem::clearNoise(double d,int s){clearOne(m_noise,s,d,[](auto&c){c.intensity=0;});}void LudoFilterSystem::clearScanlines(double d,int s){clearOne(m_scanlines,s,d,[](auto&c){c.intensity=0;c.whiteSweep=false;c.sweepIntensity=0;});}void LudoFilterSystem::clearVignette(double d,int s){clearOne(m_vignette,s,d,[](auto&c){c.intensity=0;});}void LudoFilterSystem::clearBlur(double d,int s){clearOne(m_blur,s,d,[](auto&c){c.radiusPixels=0;});}void LudoFilterSystem::clearTiltShift(double d,int s){clearOne(m_tiltShift,s,d,[](auto&c){c.blurPixels=0;});}
bool LudoFilterSystem::clearFilter(const QString&id,double d,int s){if(id==QLatin1String("chromaticAberration"))clearChromaticAberration(d,s);else if(id==QLatin1String("noise"))clearNoise(d,s);else if(id==QLatin1String("scanlines"))clearScanlines(d,s);else if(id==QLatin1String("vignette"))clearVignette(d,s);else if(id==QLatin1String("blur"))clearBlur(d,s);else if(id==QLatin1String("tiltShift"))clearTiltShift(d,s);else return false;return true;}
void LudoFilterSystem::clearAll(double d,int s){clearChromaticAberration(d,s);clearNoise(d,s);clearScanlines(d,s);clearVignette(d,s);clearBlur(d,s);clearTiltShift(d,s);}void LudoFilterSystem::clearAll(){reset();}
bool LudoFilterSystem::update(double dt){
    const double delta=qMax(0.0,dt);m_timeSeconds+=delta;
    const auto noiseCfg=noise();const auto scanCfg=scanlines();const bool scanAnimated=scanCfg.active()&&((scanCfg.whiteSweep&&scanCfg.sweepSpeed>0)||std::abs(scanCfg.scrollSpeed)>.0001||(scanCfg.style==core::ScanlineStyle::Interlaced&&scanCfg.interlaceSpeed>0));const bool animated=(noiseCfg.active()&&noiseCfg.speed>0&&noiseCfg.temporalMode!=core::NoiseTemporalMode::Static)||scanAnimated;
    bool c=false;c=updateMap(m_chromatic,delta)||c;c=updateMap(m_noise,delta)||c;c=updateMap(m_scanlines,delta)||c;c=updateMap(m_vignette,delta)||c;c=updateMap(m_blur,delta)||c;c=updateMap(m_tiltShift,delta)||c;
    for(auto it=m_scanlineSweepAge.begin();it!=m_scanlineSweepAge.end();){const auto ch=m_scanlines.constFind(it.key());if(ch==m_scanlines.constEnd()){it=m_scanlineSweepAge.erase(it);continue;}const auto& cfg=ch.value().current;if(cfg.whiteSweep&&cfg.sweepSpeed>.0001&&cfg.sweepIntensity>.0001){it.value()+=delta;++it;}else it=m_scanlineSweepAge.erase(it);}
    return c||animated;
}
bool LudoFilterSystem::hasActiveFilters()const{return activeFilterCount()>0;}bool LudoFilterSystem::isTransitioning()const{return transitioning(m_chromatic)||transitioning(m_noise)||transitioning(m_scanlines)||transitioning(m_vignette)||transitioning(m_blur)||transitioning(m_tiltShift);}int LudoFilterSystem::activeFilterCount()const{return activeCount(m_chromatic)+activeCount(m_noise)+activeCount(m_scanlines)+activeCount(m_vignette)+activeCount(m_blur)+activeCount(m_tiltShift);}bool LudoFilterSystem::affects(core::FilterRenderDomain d)const{return mapAffects(m_chromatic,d)||mapAffects(m_noise,d)||mapAffects(m_scanlines,d)||mapAffects(m_vignette,d)||mapAffects(m_blur,d)||mapAffects(m_tiltShift,d);}bool LudoFilterSystem::requiresComposedSampling(core::FilterRenderDomain d)const{return mapAffects(m_chromatic,d)||mapAffects(m_blur,d)||mapAffects(m_tiltShift,d);}bool LudoFilterSystem::fullFrameEligible()const{return hasActiveFilters()&&mapFull(m_chromatic)&&mapFull(m_noise)&&mapFull(m_scanlines)&&mapFull(m_vignette)&&mapFull(m_blur)&&mapFull(m_tiltShift);}
core::ChromaticAberrationConfig LudoFilterSystem::chromaticAberration()const{return effective(m_chromatic);}core::NoiseFilterConfig LudoFilterSystem::noise()const{return effective(m_noise);}core::ScanlineFilterConfig LudoFilterSystem::scanlines()const{return effective(m_scanlines);}core::VignetteFilterConfig LudoFilterSystem::vignette()const{return effective(m_vignette);}core::BlurFilterConfig LudoFilterSystem::blur()const{return effective(m_blur);}core::TiltShiftFilterConfig LudoFilterSystem::tiltShift()const{return effective(m_tiltShift);}
QStringList LudoFilterSystem::activeSlotDescriptions()const{QStringList out;auto add=[&](const auto&m,const QString&name){for(auto it=m.cbegin();it!=m.cend();++it)if(it.value().current.active())out<<QStringLiteral("%1 #%2").arg(name).arg(it.key());};add(m_chromatic,QStringLiteral("chromatic"));add(m_noise,QStringLiteral("noise"));add(m_scanlines,QStringLiteral("scanlines"));add(m_vignette,QStringLiteral("vignette"));add(m_blur,QStringLiteral("blur"));add(m_tiltShift,QStringLiteral("tiltShift"));return out;}

LudoFilterUniforms LudoFilterSystem::uniforms(const QSize&sz)const{LudoFilterUniforms o;const int w=qMax(1,sz.width()),h=qMax(1,sz.height());o.viewportWidth=w;o.viewportHeight=h;o.invViewportWidth=1.0f/w;o.invViewportHeight=1.0f/h;o.timeSeconds=float(std::fmod(m_timeSeconds,4096.0));const int scanSlot=effectiveSlot(m_scanlines);o.scanlineTimeSeconds=float(std::fmod(m_scanlineSweepAge.value(scanSlot,0.0),4096.0));const auto c=chromaticAberration();if(c.active()){o.chromaticIntensityPx=c.intensityPixels;o.chromaticEdgeStart=c.edgeStart;o.chromaticFalloff=c.falloff;o.chromaticMix=c.mix;o.chromaticMode=c.mode==core::ChromaticAberrationMode::Lens?1.0f:0.0f;o.chromaticScopeMask=c.scope.mask();}const auto n=noise();if(n.active()){o.noiseIntensity=n.intensity;o.noiseGrainSizePx=n.grainSizePixels;o.noiseSpeed=n.speed;o.noiseScopeMask=n.scope.mask();const int packed=n.seed*32+int(n.temporalMode)*8+int(n.style);o.noisePackedModeSeed=float(packed);o.noiseContrast=n.contrast;o.noiseColorAmount=n.colorAmount;}const auto s=scanlines();if(s.active()){o.scanlineIntensity=s.intensity;o.scanlineSpacingPx=s.spacingPixels;o.scanlineWhiteSweep=s.whiteSweep?1:0;o.sweepSpeed=s.sweepSpeed;o.sweepWidth=s.sweepWidth;o.sweepIntensity=s.sweepIntensity;o.sweepDelaySeconds=s.sweepDelaySeconds;o.scanlineScopeMask=s.scope.mask();o.scanlineStyle=float(int(s.style));o.scanlineThickness=s.thickness;o.scanlineSoftness=s.softness;o.scanlineScrollSpeed=s.scrollSpeed;o.scanlinePhasePx=s.phasePixels;o.scanlineInterlaceAmount=s.interlaceAmount;o.scanlineInterlaceSpeed=s.interlaceSpeed;o.scanlineSweepSoftness=s.sweepSoftness;o.scanlineSweepRed=s.sweepRed/255.0f;o.scanlineSweepGreen=s.sweepGreen/255.0f;o.scanlineSweepBlue=s.sweepBlue/255.0f;}const auto v=vignette();if(v.active()){o.vignetteIntensity=v.intensity;o.vignetteRadius=v.radius;o.vignetteSoftness=v.softness;o.vignetteScopeMask=v.scope.mask();}const auto b=blur();if(b.active()){o.blurRadiusPx=b.radiusPixels;o.blurDirection=b.direction==core::BlurDirection::Horizontal?0:(b.direction==core::BlurDirection::Vertical?1:2);o.blurScopeMask=b.scope.mask();o.blurStyle=float(int(b.style));o.blurStrength=b.strength;o.blurQuality=float(int(b.quality));o.blurEdgePreservation=b.edgePreservation;o.blurAngleDegrees=b.angleDegrees;}const auto t=tiltShift();if(t.active()){o.tiltBlurPx=t.blurPixels;o.tiltCenterY=t.centerY;o.tiltFocusWidth=t.focusWidth;o.tiltFalloff=t.falloff;o.tiltScopeMask=t.scope.mask();o.tiltStyle=float(int(t.style));o.tiltStrength=t.strength;o.tiltQuality=float(int(t.quality));o.tiltEdgePreservation=t.edgePreservation;o.tiltAngleDegrees=t.angleDegrees;o.tiltUpperBlur=t.upperBlurAmount;o.tiltLowerBlur=t.lowerBlurAmount;}o.activeMask=hasActiveFilters()?1:0;return o;}

void LudoFilterSystem::applyCpu(QImage&frame,QImage&scratch,core::FilterRenderDomain domain)const{auto c=chromaticAberration();auto n=noise();auto s=scanlines();auto v=vignette();auto b=blur();auto t=tiltShift();const bool ca=c.active()&&c.scope.includes(domain),na=n.active()&&n.scope.includes(domain),sa=s.active()&&s.scope.includes(domain),va=v.active()&&v.scope.includes(domain),ba=b.active()&&b.scope.includes(domain),ta=t.active()&&t.scope.includes(domain);if((!ca&&!na&&!sa&&!va&&!ba&&!ta)||frame.isNull())return;if(frame.format()!=QImage::Format_ARGB32_Premultiplied)frame=frame.convertToFormat(QImage::Format_ARGB32_Premultiplied);const int w=frame.width(),h=frame.height();
    if (ba) {
        ensureScratch(scratch,frame);
        if(b.style==core::BlurStyle::LegacyGaussian){
            if(b.direction==core::BlurDirection::Horizontal)gaussian5Pass(scratch,frame,true,b.radiusPixels);
            else if(b.direction==core::BlurDirection::Vertical)gaussian5Pass(scratch,frame,false,b.radiusPixels);
            else{gaussian5Pass(scratch,frame,true,b.radiusPixels);ensureScratch(scratch,frame);gaussian5Pass(scratch,frame,false,b.radiusPixels);}
        }else modernBlurPass(scratch,frame,b);
    }
    if (ta) {
        ensureScratch(scratch,frame);
        if(t.style==core::TiltShiftStyle::LegacyGaussian){gaussian5Pass(scratch,frame,true,0.0,&t);ensureScratch(scratch,frame);gaussian5Pass(scratch,frame,false,0.0,&t);}
        else modernTiltPass(scratch,frame,t);
    }
    if(ca){ensureScratch(scratch,frame);const double mix=c.mix,invW=1.0/qMax(1.0,w*.5),invH=1.0/qMax(1.0,h*.5);for(int y=0;y<h;++y){QRgb*dst=reinterpret_cast<QRgb*>(frame.scanLine(y));for(int x=0;x<w;++x){double dx=0,dy=0;if(c.mode==core::ChromaticAberrationMode::Normal)dx=c.intensityPixels;else{const double nx=(x+.5-w*.5)*invW,ny=(y+.5-h*.5)*invH,len=std::sqrt(nx*nx+ny*ny);if(len<=.00001)continue;const double radius=qMin(1.0,len/1.41421356237),edge=std::pow(smoothRange(c.edgeStart,1.0,radius),c.falloff);if(edge<=.00001)continue;dx=nx/len*c.intensityPixels*edge;dy=ny/len*c.intensityPixels*edge;}const int xr=qBound(0,x+int(std::lround(dx)),w-1),xb=qBound(0,x-int(std::lround(dx)),w-1),yr=qBound(0,y+int(std::lround(dy)),h-1),yb=qBound(0,y-int(std::lround(dy)),h-1);const QRgb cc=reinterpret_cast<const QRgb*>(scratch.constScanLine(y))[x],rr=reinterpret_cast<const QRgb*>(scratch.constScanLine(yr))[xr],bb=reinterpret_cast<const QRgb*>(scratch.constScanLine(yb))[xb];dst[x]=qRgba(mix8(qRed(cc),qRed(rr),mix),qGreen(cc),mix8(qBlue(cc),qBlue(bb),mix),qAlpha(cc));}}}
    const int grain=qMax(1,int(std::lround(n.grainSizePixels)));bool sweepVisible=false;const int scanSlot=effectiveSlot(m_scanlines);const double sweepPos=scanSweepPosition(m_scanlineSweepAge.value(scanSlot,0.0),s,&sweepVisible);for(int y=0;y<h;++y){QRgb*dst=reinterpret_cast<QRgb*>(frame.scanLine(y));const double yn=(y+.5)/qMax(1.0,double(h));double wave=0;if(sa&&s.intensity>0){if(s.style==core::ScanlineStyle::Legacy)wave=.5+.5*std::cos(6.28318530718*(y+.5)/s.spacingPixels);else{const double p=(y+.5+s.phasePixels+s.scrollSpeed*m_timeSeconds)/s.spacingPixels;const double frac=p-std::floor(p),dist=std::abs(frac-.5)*2.0;wave=1.0-smoothRange(s.thickness,qMin(1.0,s.thickness+s.softness),dist);if(s.style==core::ScanlineStyle::SharpCrt)wave=wave*wave*wave;if(s.style==core::ScanlineStyle::SoftCrt)wave=std::sqrt(qMax(0.0,wave));if(s.style==core::ScanlineStyle::Interlaced){const int line=int(std::floor(p));const int field=int(std::floor(m_timeSeconds*s.interlaceSpeed));if(((line+field)&1)!=0)wave*=1.0-s.interlaceAmount;}}}double sweep=0;if(sa&&s.whiteSweep&&sweepVisible&&s.sweepIntensity>0){const double d=std::abs(yn-sweepPos),inner=s.sweepWidth*(1.0-s.sweepSoftness);sweep=(1.0-smoothRange(inner,s.sweepWidth,d))*s.sweepIntensity;}for(int x=0;x<w;++x){const QRgb q=dst[x];double rr=qRed(q)/255.0,gg=qGreen(q)/255.0,bb=qBlue(q)/255.0;if(na){double mono=0,cr=0,cg=0,cb=0;if(n.style==core::NoiseStyle::LegacyBlock){mono=temporalLegacyNoise(x/grain,y/grain,n,m_timeSeconds,0);cr=temporalLegacyNoise(x/grain,y/grain,n,m_timeSeconds,211);cg=temporalLegacyNoise(x/grain,y/grain,n,m_timeSeconds,431);cb=temporalLegacyNoise(x/grain,y/grain,n,m_timeSeconds,719);}else{const double px=(x+.5)/qMax(1.0,n.grainSizePixels),py=(y+.5)/qMax(1.0,n.grainSizePixels);mono=temporalFilmNoise(px,py,n,m_timeSeconds,0);cr=temporalFilmNoise(px,py,n,m_timeSeconds,211);cg=temporalFilmNoise(px,py,n,m_timeSeconds,431);cb=temporalFilmNoise(px,py,n,m_timeSeconds,719);}mono=shapedNoise(mono,n.contrast);cr=shapedNoise(cr,n.contrast);cg=shapedNoise(cg,n.contrast);cb=shapedNoise(cb,n.contrast);const double ca=n.colorAmount;const double zr=(mono+(cr-mono)*ca)*n.intensity,zg=(mono+(cg-mono)*ca)*n.intensity,zb=(mono+(cb-mono)*ca)*n.intensity;rr=qBound(0.0,rr+zr,1.0);gg=qBound(0.0,gg+zg,1.0);bb=qBound(0.0,bb+zb,1.0);}if(sa){const double dark=1.0-wave*s.intensity;rr=qBound(0.0,rr*dark+sweep*(s.sweepRed/255.0),1.0);gg=qBound(0.0,gg*dark+sweep*(s.sweepGreen/255.0),1.0);bb=qBound(0.0,bb*dark+sweep*(s.sweepBlue/255.0),1.0);}if(va){const double nx=(x+.5)/qMax(1.0,double(w))*2-1,ny=yn*2-1,dist=std::sqrt(nx*nx+ny*ny)/1.41421356237,edge=smoothRange(v.radius,qMin(1.0,v.radius+v.softness),dist),mul=1.0-edge*v.intensity;rr*=mul;gg*=mul;bb*=mul;}dst[x]=qRgba(int(std::lround(rr*255)),int(std::lround(gg*255)),int(std::lround(bb*255)),qAlpha(q));}}
}

QJsonObject LudoFilterSystem::toJson()const{QJsonObject ages;for(auto it=m_scanlineSweepAge.cbegin();it!=m_scanlineSweepAge.cend();++it)ages.insert(QString::number(it.key()),it.value());return {{QStringLiteral("version"),3},{QStringLiteral("timeSeconds"),m_timeSeconds},{QStringLiteral("chromaticSlots"),mapJson(m_chromatic)},{QStringLiteral("noiseSlots"),mapJson(m_noise)},{QStringLiteral("scanlineSlots"),mapJson(m_scanlines)},{QStringLiteral("scanlineSweepAges"),ages},{QStringLiteral("vignetteSlots"),mapJson(m_vignette)},{QStringLiteral("blurSlots"),mapJson(m_blur)},{QStringLiteral("tiltShiftSlots"),mapJson(m_tiltShift)}};}
void LudoFilterSystem::fromJson(const QJsonObject&j){reset();if(j.isEmpty())return;const int version=j.value(QStringLiteral("version")).toInt(1);m_timeSeconds=qMax(0.0,j.value(QStringLiteral("timeSeconds")).toDouble());if(version<=2){QJsonObject cstate,nstate,sstate;if(version<=1){cstate={{QStringLiteral("current"),j.value(QStringLiteral("chromatic"))},{QStringLiteral("from"),j.value(QStringLiteral("from"))},{QStringLiteral("target"),j.value(QStringLiteral("target"))},{QStringLiteral("elapsed"),j.value(QStringLiteral("elapsed"))},{QStringLiteral("duration"),j.value(QStringLiteral("duration"))},{QStringLiteral("transitioning"),j.value(QStringLiteral("transitioning"))}};}else{cstate=j.value(QStringLiteral("chromaticState")).toObject();nstate=j.value(QStringLiteral("noiseState")).toObject();sstate=j.value(QStringLiteral("scanlineState")).toObject();}if(!cstate.isEmpty()){FilterTransitionChannel<core::ChromaticAberrationConfig> c;channelRead(c,cstate,[](const QVariantMap&v){return core::ChromaticAberrationConfig::fromVariantMap(v);});m_chromatic.insert(1,c);}if(!nstate.isEmpty()){FilterTransitionChannel<core::NoiseFilterConfig> c;channelRead(c,nstate,[](const QVariantMap&v){return core::NoiseFilterConfig::fromVariantMap(v);});m_noise.insert(1,c);}if(!sstate.isEmpty()){FilterTransitionChannel<core::ScanlineFilterConfig> c;channelRead(c,sstate,[](const QVariantMap&v){return core::ScanlineFilterConfig::fromVariantMap(v);});m_scanlines.insert(1,c);}return;}mapRead(m_chromatic,j.value(QStringLiteral("chromaticSlots")).toObject(),[](const QVariantMap&v){return core::ChromaticAberrationConfig::fromVariantMap(v);});mapRead(m_noise,j.value(QStringLiteral("noiseSlots")).toObject(),[](const QVariantMap&v){return core::NoiseFilterConfig::fromVariantMap(v);});mapRead(m_scanlines,j.value(QStringLiteral("scanlineSlots")).toObject(),[](const QVariantMap&v){return core::ScanlineFilterConfig::fromVariantMap(v);});const QJsonObject ages=j.value(QStringLiteral("scanlineSweepAges")).toObject();for(auto it=ages.begin();it!=ages.end();++it){bool ok=false;const int slot=it.key().toInt(&ok);if(ok&&slot>=1&&slot<=99&&m_scanlines.contains(slot))m_scanlineSweepAge.insert(slot,qMax(0.0,it.value().toDouble()));}for(auto it=m_scanlines.cbegin();it!=m_scanlines.cend();++it)if(it.value().current.whiteSweep&&!m_scanlineSweepAge.contains(it.key()))m_scanlineSweepAge.insert(it.key(),0.0);mapRead(m_vignette,j.value(QStringLiteral("vignetteSlots")).toObject(),[](const QVariantMap&v){return core::VignetteFilterConfig::fromVariantMap(v);});mapRead(m_blur,j.value(QStringLiteral("blurSlots")).toObject(),[](const QVariantMap&v){return core::BlurFilterConfig::fromVariantMap(v);});mapRead(m_tiltShift,j.value(QStringLiteral("tiltShiftSlots")).toObject(),[](const QVariantMap&v){return core::TiltShiftFilterConfig::fromVariantMap(v);});}

} // namespace game
