#include "Database.h"
#include <QCoreApplication>
namespace core {
QStringList databaseCategories(){return{"actors","classes","skills","items","weapons","armors","states","enemies","troops","animations","quests"};}
QString databaseCategoryLabel(const QString&id){if(id=="actors")return QCoreApplication::translate("Database","Personagens");if(id=="classes")return QCoreApplication::translate("Database","Classes");if(id=="skills")return QCoreApplication::translate("Database","Habilidades");if(id=="items")return QCoreApplication::translate("Database","Itens");if(id=="weapons")return QCoreApplication::translate("Database","Armas");if(id=="armors")return QCoreApplication::translate("Database","Armaduras");if(id=="states")return QCoreApplication::translate("Database","Estados");if(id=="enemies")return QCoreApplication::translate("Database","Inimigos");if(id=="troops")return QCoreApplication::translate("Database","Grupos de inimigos");if(id=="animations")return QCoreApplication::translate("Database","Animações");if(id=="quests")return QCoreApplication::translate("Database","Missões");return id;}

void populateDefaultDatabase(QHash<QString,QVector<DatabaseRecord>>& database)
{
    database.clear();for(const QString& category:databaseCategories())database[category]={};
    DatabaseRecord klass;klass.number=1;klass.name=QCoreApplication::translate("Database","Aventureiro");klass.data={{QStringLiteral("hp"),100},{QStringLiteral("mp"),30},{QStringLiteral("attack"),10},{QStringLiteral("defense"),8},{QStringLiteral("agility"),10},{QStringLiteral("hpGrowth"),12},{QStringLiteral("mpGrowth"),4},{QStringLiteral("attackGrowth"),2},{QStringLiteral("defenseGrowth"),2},{QStringLiteral("agilityGrowth"),1},{QStringLiteral("maxLevel"),99}};database[QStringLiteral("classes")].push_back(klass);
    DatabaseRecord skill;skill.number=1;skill.name=QCoreApplication::translate("Database","Golpe");skill.description=QCoreApplication::translate("Database","Um ataque físico concentrado.");skill.data={{QStringLiteral("power"),12},{QStringLiteral("mpCost"),0},{QStringLiteral("scope"),QStringLiteral("enemyOne")},{QStringLiteral("hitRate"),95},{QStringLiteral("critical"),10},{QStringLiteral("useChance"),100}};database[QStringLiteral("skills")].push_back(skill);
    DatabaseRecord actor;actor.number=1;actor.name=QCoreApplication::translate("Database","Herói");actor.data={{QStringLiteral("classId"),klass.id},{QStringLiteral("initialParty"),true},{QStringLiteral("initialLevel"),1},{QStringLiteral("initialGold"),100},{QStringLiteral("maxLevel"),99},{QStringLiteral("skillIds"),QStringList{skill.id}}};database[QStringLiteral("actors")].push_back(actor);
    DatabaseRecord potion;potion.number=1;potion.name=QCoreApplication::translate("Database","Poção");potion.description=QCoreApplication::translate("Database","Recupera 50 pontos de HP.");potion.data={{QStringLiteral("price"),50},{QStringLiteral("initialAmount"),3},{QStringLiteral("healHp"),50},{QStringLiteral("healMp"),0},{QStringLiteral("consumable"),true},{QStringLiteral("scope"),QStringLiteral("allyOne")}};database[QStringLiteral("items")].push_back(potion);
    DatabaseRecord sword;sword.number=1;sword.name=QCoreApplication::translate("Database","Espada curta");sword.data={{QStringLiteral("price"),100},{QStringLiteral("initialAmount"),1},{QStringLiteral("attack"),5},{QStringLiteral("slot"),QStringLiteral("weapon")}};database[QStringLiteral("weapons")].push_back(sword);
    DatabaseRecord armor;armor.number=1;armor.name=QCoreApplication::translate("Database","Túnica");armor.data={{QStringLiteral("price"),80},{QStringLiteral("initialAmount"),1},{QStringLiteral("defense"),3},{QStringLiteral("slot"),QStringLiteral("armor")}};database[QStringLiteral("armors")].push_back(armor);
    DatabaseRecord state;state.number=1;state.name=QCoreApplication::translate("Database","Veneno");state.data={{QStringLiteral("duration"),4},{QStringLiteral("attackRate"),1.0},{QStringLiteral("defenseRate"),1.0},{QStringLiteral("agilityRate"),1.0},{QStringLiteral("hpDamageRate"),5}};database[QStringLiteral("states")].push_back(state);
    DatabaseRecord enemy;enemy.number=1;enemy.name=QCoreApplication::translate("Database","Slime");enemy.data={{QStringLiteral("hp"),35},{QStringLiteral("mp"),0},{QStringLiteral("attack"),8},{QStringLiteral("defense"),3},{QStringLiteral("agility"),6},{QStringLiteral("hitRate"),90},{QStringLiteral("evasion"),3},{QStringLiteral("critical"),3},{QStringLiteral("experience"),12},{QStringLiteral("gold"),8},{QStringLiteral("lootId"),potion.id},{QStringLiteral("lootChance"),20}};database[QStringLiteral("enemies")].push_back(enemy);
    DatabaseRecord troop;troop.number=1;troop.name=QCoreApplication::translate("Database","2 Slimes");troop.data={{QStringLiteral("enemyIds"),QStringList{enemy.id,enemy.id}},{QStringLiteral("encounterWeight"),10}};database[QStringLiteral("troops")].push_back(troop);
    DatabaseRecord animation;animation.number=1;animation.name=QCoreApplication::translate("Database","Golpe");animation.data={{QStringLiteral("frames"),4}};database[QStringLiteral("animations")].push_back(animation);
    DatabaseRecord quest;quest.number=1;quest.name=QCoreApplication::translate("Database","Primeiros passos");quest.description=QCoreApplication::translate("Database","Explore o mapa e converse com os moradores.");quest.data={{QStringLiteral("target"),1},{QStringLiteral("hiddenUntilStarted"),true}};database[QStringLiteral("quests")].push_back(quest);
}
}
