#include "FilterSystem.h"

#include <QObject>
#include <QtGlobal>
#include <cmath>

namespace core {
namespace {
double finiteOr(double value, double fallback) { return std::isfinite(value) ? value : fallback; }
void appendScope(QVariantMap& out, const FilterScopeConfig& scope) {
    out.insert(QStringLiteral("affectWorld"), scope.world);
    out.insert(QStringLiteral("affectPictures"), scope.pictures);
    out.insert(QStringLiteral("affectHud"), scope.hud);
}
}

int FilterScopeConfig::mask() const { return (world?1:0)|(pictures?2:0)|(hud?4:0); }
bool FilterScopeConfig::includes(FilterRenderDomain domain) const { return (mask() & int(domain)) != 0; }
QVariantMap FilterScopeConfig::toVariantMap() const { return {{QStringLiteral("affectWorld"),world},{QStringLiteral("affectPictures"),pictures},{QStringLiteral("affectHud"),hud}}; }
FilterScopeConfig FilterScopeConfig::fromVariantMap(const QVariantMap& p) {
    FilterScopeConfig out; out.world=p.value(QStringLiteral("affectWorld"),true).toBool(); out.pictures=p.value(QStringLiteral("affectPictures"),false).toBool(); out.hud=p.value(QStringLiteral("affectHud"),false).toBool(); return out;
}

QString chromaticAberrationModeId(ChromaticAberrationMode mode){return mode==ChromaticAberrationMode::Normal?QStringLiteral("normal"):QStringLiteral("lens");}
QString chromaticAberrationModeLabel(ChromaticAberrationMode mode){return mode==ChromaticAberrationMode::Normal?QObject::tr("Normal"):QObject::tr("Lente");}
ChromaticAberrationMode chromaticAberrationModeFromId(const QString& id){return id.compare(QStringLiteral("normal"),Qt::CaseInsensitive)==0?ChromaticAberrationMode::Normal:ChromaticAberrationMode::Lens;}

void ChromaticAberrationConfig::normalize(){intensityPixels=qBound(0.0,finiteOr(intensityPixels,0.0),ChromaticAberrationMaxPixels);edgeStart=qBound(0.0,finiteOr(edgeStart,.55),.95);falloff=qBound(.25,finiteOr(falloff,2.0),8.0);mix=qBound(0.0,finiteOr(mix,1.0),1.0);}
QVariantMap ChromaticAberrationConfig::toVariantMap() const {auto c=*this;c.normalize();QVariantMap out{{QStringLiteral("mode"),chromaticAberrationModeId(c.mode)},{QStringLiteral("intensity"),c.intensityPixels},{QStringLiteral("edgeStart"),c.edgeStart},{QStringLiteral("falloff"),c.falloff},{QStringLiteral("mix"),c.mix}};appendScope(out,c.scope);return out;}
ChromaticAberrationConfig ChromaticAberrationConfig::fromVariantMap(const QVariantMap& p){ChromaticAberrationConfig out;out.mode=chromaticAberrationModeFromId(p.value(QStringLiteral("mode"),QStringLiteral("lens")).toString());out.intensityPixels=p.value(QStringLiteral("intensity"),4.0).toDouble();out.edgeStart=p.value(QStringLiteral("edgeStart"),.55).toDouble();out.falloff=p.value(QStringLiteral("falloff"),2.0).toDouble();out.mix=p.value(QStringLiteral("mix"),1.0).toDouble();if(out.mix>1.0)out.mix/=100.0;out.scope=FilterScopeConfig::fromVariantMap(p);out.normalize();return out;}

QString noiseStyleId(NoiseStyle style){return style==NoiseStyle::FilmGrain?QStringLiteral("film"):QStringLiteral("legacy");}
QString noiseStyleLabel(NoiseStyle style){return style==NoiseStyle::FilmGrain?QObject::tr("Granulação de filme"):QObject::tr("Blocos clássicos");}
NoiseStyle noiseStyleFromId(const QString& id){return id.compare(QStringLiteral("film"),Qt::CaseInsensitive)==0?NoiseStyle::FilmGrain:NoiseStyle::LegacyBlock;}
QString noiseTemporalModeId(NoiseTemporalMode mode){switch(mode){case NoiseTemporalMode::Static:return QStringLiteral("static");case NoiseTemporalMode::Drift:return QStringLiteral("drift");case NoiseTemporalMode::Smooth:return QStringLiteral("smooth");default:return QStringLiteral("flicker");}}
QString noiseTemporalModeLabel(NoiseTemporalMode mode){switch(mode){case NoiseTemporalMode::Static:return QObject::tr("Estático");case NoiseTemporalMode::Drift:return QObject::tr("Deslocamento");case NoiseTemporalMode::Smooth:return QObject::tr("Suave");default:return QObject::tr("Oscilação");}}
NoiseTemporalMode noiseTemporalModeFromId(const QString& id){if(id.compare(QStringLiteral("static"),Qt::CaseInsensitive)==0)return NoiseTemporalMode::Static;if(id.compare(QStringLiteral("drift"),Qt::CaseInsensitive)==0)return NoiseTemporalMode::Drift;if(id.compare(QStringLiteral("smooth"),Qt::CaseInsensitive)==0)return NoiseTemporalMode::Smooth;return NoiseTemporalMode::Flicker;}

void NoiseFilterConfig::normalize(){intensity=qBound(0.0,finiteOr(intensity,0.0),1.0);grainSizePixels=qBound(1.0,finiteOr(grainSizePixels,2.0),NoiseMaxGrainPixels);speed=qBound(0.0,finiteOr(speed,1.0),NoiseMaxSpeed);seed=qBound(0,seed,65535);contrast=qBound(.25,finiteOr(contrast,1.0),NoiseMaxContrast);colorAmount=qBound(0.0,finiteOr(colorAmount,0.0),1.0);}
QVariantMap NoiseFilterConfig::toVariantMap() const {auto c=*this;c.normalize();QVariantMap out{{QStringLiteral("intensity"),c.intensity},{QStringLiteral("size"),c.grainSizePixels},{QStringLiteral("speed"),c.speed},{QStringLiteral("style"),noiseStyleId(c.style)},{QStringLiteral("temporal"),noiseTemporalModeId(c.temporalMode)},{QStringLiteral("seed"),c.seed},{QStringLiteral("contrast"),c.contrast},{QStringLiteral("colorAmount"),c.colorAmount}};appendScope(out,c.scope);return out;}
NoiseFilterConfig NoiseFilterConfig::fromVariantMap(const QVariantMap& p){NoiseFilterConfig out;out.intensity=p.value(QStringLiteral("intensity"),.12).toDouble();if(out.intensity>1.0)out.intensity/=100.0;out.grainSizePixels=p.value(QStringLiteral("size"),2.0).toDouble();out.speed=p.value(QStringLiteral("speed"),1.0).toDouble();out.style=noiseStyleFromId(p.value(QStringLiteral("style"),QStringLiteral("legacy")).toString());out.temporalMode=noiseTemporalModeFromId(p.value(QStringLiteral("temporal"),QStringLiteral("flicker")).toString());out.seed=p.value(QStringLiteral("seed"),0).toInt();out.contrast=p.value(QStringLiteral("contrast"),1.0).toDouble();out.colorAmount=p.value(QStringLiteral("colorAmount"),0.0).toDouble();if(out.colorAmount>1.0)out.colorAmount/=100.0;out.scope=FilterScopeConfig::fromVariantMap(p);out.normalize();return out;}

QString scanlineStyleId(ScanlineStyle style){switch(style){case ScanlineStyle::SoftCrt:return QStringLiteral("softCrt");case ScanlineStyle::SharpCrt:return QStringLiteral("sharpCrt");case ScanlineStyle::Interlaced:return QStringLiteral("interlaced");default:return QStringLiteral("legacy");}}
QString scanlineStyleLabel(ScanlineStyle style){switch(style){case ScanlineStyle::SoftCrt:return QObject::tr("CRT suave");case ScanlineStyle::SharpCrt:return QObject::tr("CRT nítido");case ScanlineStyle::Interlaced:return QObject::tr("Entrelaçado");default:return QObject::tr("Clássico");}}
ScanlineStyle scanlineStyleFromId(const QString& id){if(id.compare(QStringLiteral("softCrt"),Qt::CaseInsensitive)==0)return ScanlineStyle::SoftCrt;if(id.compare(QStringLiteral("sharpCrt"),Qt::CaseInsensitive)==0)return ScanlineStyle::SharpCrt;if(id.compare(QStringLiteral("interlaced"),Qt::CaseInsensitive)==0)return ScanlineStyle::Interlaced;return ScanlineStyle::Legacy;}

void ScanlineFilterConfig::normalize(){intensity=qBound(0.0,finiteOr(intensity,0.0),1.0);spacingPixels=qBound(2.0,finiteOr(spacingPixels,3.0),ScanlineMaxSpacingPixels);thickness=qBound(.05,finiteOr(thickness,.50),.95);softness=qBound(0.0,finiteOr(softness,.22),.95);phasePixels=qBound(-ScanlineMaxSpacingPixels,finiteOr(phasePixels,0.0),ScanlineMaxSpacingPixels);scrollSpeed=qBound(-ScanlineMaxScrollSpeed,finiteOr(scrollSpeed,0.0),ScanlineMaxScrollSpeed);interlaceAmount=qBound(0.0,finiteOr(interlaceAmount,.55),1.0);interlaceSpeed=qBound(0.0,finiteOr(interlaceSpeed,60.0),ScanlineMaxInterlaceSpeed);sweepSpeed=qBound(0.0,finiteOr(sweepSpeed,.35),ScanlineMaxSweepSpeed);sweepWidth=qBound(.005,finiteOr(sweepWidth,.055),.5);sweepSoftness=qBound(0.0,finiteOr(sweepSoftness,1.0),1.0);sweepIntensity=qBound(0.0,finiteOr(sweepIntensity,.45),1.0);sweepRed=qBound(0,sweepRed,255);sweepGreen=qBound(0,sweepGreen,255);sweepBlue=qBound(0,sweepBlue,255);sweepDelaySeconds=qBound(0.0,finiteOr(sweepDelaySeconds,0.0),ScanlineMaxSweepDelaySeconds);}
QVariantMap ScanlineFilterConfig::toVariantMap() const {auto c=*this;c.normalize();QVariantMap out{{QStringLiteral("intensity"),c.intensity},{QStringLiteral("spacing"),c.spacingPixels},{QStringLiteral("style"),scanlineStyleId(c.style)},{QStringLiteral("thickness"),c.thickness},{QStringLiteral("softness"),c.softness},{QStringLiteral("phase"),c.phasePixels},{QStringLiteral("scrollSpeed"),c.scrollSpeed},{QStringLiteral("interlaceAmount"),c.interlaceAmount},{QStringLiteral("interlaceSpeed"),c.interlaceSpeed},{QStringLiteral("whiteSweep"),c.whiteSweep},{QStringLiteral("sweepSpeed"),c.sweepSpeed},{QStringLiteral("sweepWidth"),c.sweepWidth},{QStringLiteral("sweepSoftness"),c.sweepSoftness},{QStringLiteral("sweepIntensity"),c.sweepIntensity},{QStringLiteral("sweepRed"),c.sweepRed},{QStringLiteral("sweepGreen"),c.sweepGreen},{QStringLiteral("sweepBlue"),c.sweepBlue},{QStringLiteral("sweepDelay"),c.sweepDelaySeconds*60.0}};appendScope(out,c.scope);return out;}
ScanlineFilterConfig ScanlineFilterConfig::fromVariantMap(const QVariantMap& p){ScanlineFilterConfig out;out.intensity=p.value(QStringLiteral("intensity"),.28).toDouble();if(out.intensity>1.0)out.intensity/=100.0;out.spacingPixels=p.value(QStringLiteral("spacing"),3.0).toDouble();out.style=scanlineStyleFromId(p.value(QStringLiteral("style"),QStringLiteral("legacy")).toString());out.thickness=p.value(QStringLiteral("thickness"),.50).toDouble();if(out.thickness>1.0)out.thickness/=100.0;out.softness=p.value(QStringLiteral("softness"),.22).toDouble();if(out.softness>1.0)out.softness/=100.0;out.phasePixels=p.value(QStringLiteral("phase"),0.0).toDouble();out.scrollSpeed=p.value(QStringLiteral("scrollSpeed"),0.0).toDouble();out.interlaceAmount=p.value(QStringLiteral("interlaceAmount"),.55).toDouble();if(out.interlaceAmount>1.0)out.interlaceAmount/=100.0;out.interlaceSpeed=p.value(QStringLiteral("interlaceSpeed"),60.0).toDouble();out.whiteSweep=p.value(QStringLiteral("whiteSweep"),false).toBool();out.sweepSpeed=p.value(QStringLiteral("sweepSpeed"),.35).toDouble();out.sweepWidth=p.value(QStringLiteral("sweepWidth"),.055).toDouble();if(out.sweepWidth>1.0)out.sweepWidth/=100.0;out.sweepSoftness=p.value(QStringLiteral("sweepSoftness"),1.0).toDouble();if(out.sweepSoftness>1.0)out.sweepSoftness/=100.0;out.sweepIntensity=p.value(QStringLiteral("sweepIntensity"),.45).toDouble();if(out.sweepIntensity>1.0)out.sweepIntensity/=100.0;out.sweepRed=p.value(QStringLiteral("sweepRed"),255).toInt();out.sweepGreen=p.value(QStringLiteral("sweepGreen"),255).toInt();out.sweepBlue=p.value(QStringLiteral("sweepBlue"),255).toInt();out.sweepDelaySeconds=qMax(0.0,p.value(QStringLiteral("sweepDelay"),0.0).toDouble()/60.0);out.scope=FilterScopeConfig::fromVariantMap(p);out.normalize();return out;}

void VignetteFilterConfig::normalize(){intensity=qBound(0.0,finiteOr(intensity,0.0),1.0);radius=qBound(.05,finiteOr(radius,.68),1.0);softness=qBound(.01,finiteOr(softness,.28),1.0);}
QVariantMap VignetteFilterConfig::toVariantMap() const {auto c=*this;c.normalize();QVariantMap out{{QStringLiteral("intensity"),c.intensity},{QStringLiteral("radius"),c.radius},{QStringLiteral("softness"),c.softness}};appendScope(out,c.scope);return out;}
VignetteFilterConfig VignetteFilterConfig::fromVariantMap(const QVariantMap& p){VignetteFilterConfig out;out.intensity=p.value(QStringLiteral("intensity"),.45).toDouble();if(out.intensity>1.0)out.intensity/=100.0;out.radius=p.value(QStringLiteral("radius"),.68).toDouble();if(out.radius>1.0)out.radius/=100.0;out.softness=p.value(QStringLiteral("softness"),.28).toDouble();if(out.softness>1.0)out.softness/=100.0;out.scope=FilterScopeConfig::fromVariantMap(p);out.normalize();return out;}

QString blurDirectionId(BlurDirection d){switch(d){case BlurDirection::Horizontal:return QStringLiteral("horizontal");case BlurDirection::Vertical:return QStringLiteral("vertical");case BlurDirection::Full:return QStringLiteral("full");}return QStringLiteral("full");}
QString blurDirectionLabel(BlurDirection d){switch(d){case BlurDirection::Horizontal:return QObject::tr("Horizontal");case BlurDirection::Vertical:return QObject::tr("Vertical");case BlurDirection::Full:return QObject::tr("Completo");}return QObject::tr("Completo");}
BlurDirection blurDirectionFromId(const QString& id){if(id.compare(QStringLiteral("horizontal"),Qt::CaseInsensitive)==0)return BlurDirection::Horizontal;if(id.compare(QStringLiteral("vertical"),Qt::CaseInsensitive)==0)return BlurDirection::Vertical;return BlurDirection::Full;}
QString blurStyleId(BlurStyle s){switch(s){case BlurStyle::GaussianSoft:return QStringLiteral("gaussianSoft");case BlurStyle::GaussianSharp:return QStringLiteral("gaussianSharp");case BlurStyle::Box:return QStringLiteral("box");case BlurStyle::Directional:return QStringLiteral("directional");case BlurStyle::Pixel:return QStringLiteral("pixel");default:return QStringLiteral("legacy");}}
QString blurStyleLabel(BlurStyle s){switch(s){case BlurStyle::GaussianSoft:return QObject::tr("Gaussiano suave");case BlurStyle::GaussianSharp:return QObject::tr("Gaussiano definido");case BlurStyle::Box:return QObject::tr("Desfoque em caixa");case BlurStyle::Directional:return QObject::tr("Desfoque direcional");case BlurStyle::Pixel:return QObject::tr("Desfoque em pixels");default:return QObject::tr("Gaussiano clássico");}}
BlurStyle blurStyleFromId(const QString& id){if(id.compare(QStringLiteral("gaussianSoft"),Qt::CaseInsensitive)==0)return BlurStyle::GaussianSoft;if(id.compare(QStringLiteral("gaussianSharp"),Qt::CaseInsensitive)==0)return BlurStyle::GaussianSharp;if(id.compare(QStringLiteral("box"),Qt::CaseInsensitive)==0)return BlurStyle::Box;if(id.compare(QStringLiteral("directional"),Qt::CaseInsensitive)==0)return BlurStyle::Directional;if(id.compare(QStringLiteral("pixel"),Qt::CaseInsensitive)==0)return BlurStyle::Pixel;return BlurStyle::LegacyGaussian;}
QString blurQualityId(BlurQuality q){switch(q){case BlurQuality::Low:return QStringLiteral("low");case BlurQuality::High:return QStringLiteral("high");case BlurQuality::Ultra:return QStringLiteral("ultra");default:return QStringLiteral("medium");}}
QString blurQualityLabel(BlurQuality q){switch(q){case BlurQuality::Low:return QObject::tr("Baixa");case BlurQuality::High:return QObject::tr("Alta");case BlurQuality::Ultra:return QObject::tr("Ultra");default:return QObject::tr("Média");}}
BlurQuality blurQualityFromId(const QString& id){if(id.compare(QStringLiteral("low"),Qt::CaseInsensitive)==0)return BlurQuality::Low;if(id.compare(QStringLiteral("high"),Qt::CaseInsensitive)==0)return BlurQuality::High;if(id.compare(QStringLiteral("ultra"),Qt::CaseInsensitive)==0)return BlurQuality::Ultra;return BlurQuality::Medium;}
void BlurFilterConfig::normalize(){radiusPixels=qBound(0.0,finiteOr(radiusPixels,0.0),BlurMaxRadiusPixels);strength=qBound(0.0,finiteOr(strength,1.0),1.0);edgePreservation=qBound(0.0,finiteOr(edgePreservation,0.0),1.0);angleDegrees=finiteOr(angleDegrees,0.0);while(angleDegrees>180.0)angleDegrees-=360.0;while(angleDegrees<-180.0)angleDegrees+=360.0;}
QVariantMap BlurFilterConfig::toVariantMap() const {auto c=*this;c.normalize();QVariantMap out{{QStringLiteral("radius"),c.radiusPixels},{QStringLiteral("direction"),blurDirectionId(c.direction)},{QStringLiteral("style"),blurStyleId(c.style)},{QStringLiteral("quality"),blurQualityId(c.quality)},{QStringLiteral("strength"),c.strength},{QStringLiteral("edgePreservation"),c.edgePreservation},{QStringLiteral("angle"),c.angleDegrees}};appendScope(out,c.scope);return out;}
BlurFilterConfig BlurFilterConfig::fromVariantMap(const QVariantMap& p){BlurFilterConfig out;out.radiusPixels=p.value(QStringLiteral("radius"),4.0).toDouble();out.direction=blurDirectionFromId(p.value(QStringLiteral("direction"),QStringLiteral("full")).toString());out.style=blurStyleFromId(p.value(QStringLiteral("style"),QStringLiteral("legacy")).toString());out.quality=blurQualityFromId(p.value(QStringLiteral("quality"),QStringLiteral("medium")).toString());out.strength=p.value(QStringLiteral("strength"),1.0).toDouble();if(out.strength>1.0)out.strength/=100.0;out.edgePreservation=p.value(QStringLiteral("edgePreservation"),0.0).toDouble();if(out.edgePreservation>1.0)out.edgePreservation/=100.0;out.angleDegrees=p.value(QStringLiteral("angle"),0.0).toDouble();out.scope=FilterScopeConfig::fromVariantMap(p);out.normalize();return out;}

QString tiltShiftStyleId(TiltShiftStyle s){switch(s){case TiltShiftStyle::GaussianSoft:return QStringLiteral("gaussianSoft");case TiltShiftStyle::GaussianSharp:return QStringLiteral("gaussianSharp");case TiltShiftStyle::Box:return QStringLiteral("box");default:return QStringLiteral("legacy");}}
QString tiltShiftStyleLabel(TiltShiftStyle s){switch(s){case TiltShiftStyle::GaussianSoft:return QObject::tr("Gaussiano suave");case TiltShiftStyle::GaussianSharp:return QObject::tr("Gaussiano definido");case TiltShiftStyle::Box:return QObject::tr("Foco em caixa");default:return QObject::tr("Gaussiano clássico");}}
TiltShiftStyle tiltShiftStyleFromId(const QString& id){if(id.compare(QStringLiteral("gaussianSoft"),Qt::CaseInsensitive)==0)return TiltShiftStyle::GaussianSoft;if(id.compare(QStringLiteral("gaussianSharp"),Qt::CaseInsensitive)==0)return TiltShiftStyle::GaussianSharp;if(id.compare(QStringLiteral("box"),Qt::CaseInsensitive)==0)return TiltShiftStyle::Box;return TiltShiftStyle::LegacyGaussian;}
void TiltShiftFilterConfig::normalize(){blurPixels=qBound(0.0,finiteOr(blurPixels,0.0),TiltShiftMaxBlurPixels);centerY=qBound(0.0,finiteOr(centerY,.5),1.0);focusWidth=qBound(.01,finiteOr(focusWidth,.25),1.0);falloff=qBound(.01,finiteOr(falloff,.2),1.0);strength=qBound(0.0,finiteOr(strength,1.0),1.0);edgePreservation=qBound(0.0,finiteOr(edgePreservation,0.0),1.0);angleDegrees=finiteOr(angleDegrees,0.0);while(angleDegrees>180.0)angleDegrees-=360.0;while(angleDegrees<-180.0)angleDegrees+=360.0;upperBlurAmount=qBound(0.0,finiteOr(upperBlurAmount,1.0),2.0);lowerBlurAmount=qBound(0.0,finiteOr(lowerBlurAmount,1.0),2.0);}
QVariantMap TiltShiftFilterConfig::toVariantMap() const {auto c=*this;c.normalize();QVariantMap out{{QStringLiteral("blur"),c.blurPixels},{QStringLiteral("centerY"),c.centerY},{QStringLiteral("focusWidth"),c.focusWidth},{QStringLiteral("falloff"),c.falloff},{QStringLiteral("style"),tiltShiftStyleId(c.style)},{QStringLiteral("quality"),blurQualityId(c.quality)},{QStringLiteral("strength"),c.strength},{QStringLiteral("edgePreservation"),c.edgePreservation},{QStringLiteral("angle"),c.angleDegrees},{QStringLiteral("upperBlur"),c.upperBlurAmount},{QStringLiteral("lowerBlur"),c.lowerBlurAmount}};appendScope(out,c.scope);return out;}
TiltShiftFilterConfig TiltShiftFilterConfig::fromVariantMap(const QVariantMap& p){TiltShiftFilterConfig out;out.blurPixels=p.value(QStringLiteral("blur"),6.0).toDouble();out.centerY=p.value(QStringLiteral("centerY"),.5).toDouble();if(out.centerY>1.0)out.centerY/=100.0;out.focusWidth=p.value(QStringLiteral("focusWidth"),.25).toDouble();if(out.focusWidth>1.0)out.focusWidth/=100.0;out.falloff=p.value(QStringLiteral("falloff"),.2).toDouble();if(out.falloff>1.0)out.falloff/=100.0;out.style=tiltShiftStyleFromId(p.value(QStringLiteral("style"),QStringLiteral("legacy")).toString());out.quality=blurQualityFromId(p.value(QStringLiteral("quality"),QStringLiteral("medium")).toString());out.strength=p.value(QStringLiteral("strength"),1.0).toDouble();if(out.strength>1.0)out.strength/=100.0;out.edgePreservation=p.value(QStringLiteral("edgePreservation"),0.0).toDouble();if(out.edgePreservation>1.0)out.edgePreservation/=100.0;out.angleDegrees=p.value(QStringLiteral("angle"),0.0).toDouble();out.upperBlurAmount=p.value(QStringLiteral("upperBlur"),1.0).toDouble();if(out.upperBlurAmount>2.0)out.upperBlurAmount/=100.0;out.lowerBlurAmount=p.value(QStringLiteral("lowerBlur"),1.0).toDouble();if(out.lowerBlurAmount>2.0)out.lowerBlurAmount/=100.0;out.scope=FilterScopeConfig::fromVariantMap(p);out.normalize();return out;}

QString ludoFilterTypeId(LudoFilterType t){switch(t){case LudoFilterType::ChromaticAberration:return QStringLiteral("chromaticAberration");case LudoFilterType::Noise:return QStringLiteral("noise");case LudoFilterType::Scanlines:return QStringLiteral("scanlines");case LudoFilterType::Vignette:return QStringLiteral("vignette");case LudoFilterType::Blur:return QStringLiteral("blur");case LudoFilterType::TiltShift:return QStringLiteral("tiltShift");}return QStringLiteral("chromaticAberration");}
QString ludoFilterTypeLabel(LudoFilterType t){switch(t){case LudoFilterType::ChromaticAberration:return QObject::tr("Aberração cromática");case LudoFilterType::Noise:return QObject::tr("Ruído e granulação");case LudoFilterType::Scanlines:return QObject::tr("Linhas de tela");case LudoFilterType::Vignette:return QObject::tr("Vinheta");case LudoFilterType::Blur:return QObject::tr("Desfoque");case LudoFilterType::TiltShift:return QObject::tr("Foco seletivo (Tilt-Shift)");}return QObject::tr("Filtro");}
bool ludoFilterTypeFromId(const QString& id,LudoFilterType* out){LudoFilterType v;if(id==QLatin1String("chromaticAberration"))v=LudoFilterType::ChromaticAberration;else if(id==QLatin1String("noise"))v=LudoFilterType::Noise;else if(id==QLatin1String("scanlines"))v=LudoFilterType::Scanlines;else if(id==QLatin1String("vignette"))v=LudoFilterType::Vignette;else if(id==QLatin1String("blur"))v=LudoFilterType::Blur;else if(id==QLatin1String("tiltShift"))v=LudoFilterType::TiltShift;else return false;if(out)*out=v;return true;}
int normalizedLudoFilterSlot(const QVariantMap& p){return qBound(LudoFilterMinSlot,p.value(QStringLiteral("slot"),1).toInt(),LudoFilterMaxSlot);}

} // namespace core
